@echo off
echo Building backend project...
echo %0
dotnet build  %0\..\..\src\Platform.sln
pushd  %0\..\..\src\Platform.Client
echo Downloading client dependencies...
call npm i
echo Building frontend project...
call npm run build
popd
echo BUILD FINISHED
set /p DUMMY=Hit ENTER to continue...